version: '3.7'

services:
  django:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/home/daniel/django/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hack_postgres_user
      - POSTGRES_PASSWORD=hack_postgres_password
      - POSTGRES_DB=hack_postgres_db

volumes:
  postgres_data:
