# Generated by Django 3.0.8 on 2020-07-06 14:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='В обработке', max_length=25, verbose_name='Статус заказа')),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 7, 6, 17, 23, 16, 506166), verbose_name='Дата')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.Cart.vue')),
            ],
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
