# Generated by Django 3.0.8 on 2020-07-13 17:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20200706_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 13, 20, 4, 6, 337730), verbose_name='Дата'),
        ),
    ]
