# Generated by Django 3.0.8 on 2020-07-14 16:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20200713_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 14, 19, 2, 25, 299379), verbose_name='Дата'),
        ),
    ]
