# Generated by Django 3.0.8 on 2020-07-17 14:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20200714_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 17, 21, 24, 2, 93448), verbose_name='Дата'),
        ),
    ]
