# Generated by Django 3.0.8 on 2020-07-02 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('tagline', models.CharField(db_index=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50)),
                ('image', models.ImageField(default=None, upload_to='')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('description', models.CharField(max_length=250)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='order.Category')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
    ]
